CREATE TABLE IF NOT EXISTS `monitor_disk_indicator` (
    `id`               BIGINT UNSIGNED AUTO_INCREMENT   COMMENT 'id',
    `name`             VARCHAR(50)   NOT NULL           COMMENT '磁盘名',
    `host_name`        VARCHAR(50)   NOT NULL           COMMENT '机器名称',
    `host_ip`          VARCHAR(50)   NOT NULL           COMMENT '机器ip',
    `device`           VARCHAR(50)   NOT NULL           COMMENT 'device',
    `mount`            VARCHAR(100)                     COMMENT '挂载点',
    `serial_num`       VARCHAR(100)                     COMMENT '序列码',
    `read_count`       BIGINT                           COMMENT '读次数',
    `write_count`      BIGINT                           COMMENT '写次数',
    `read_bytes`       BIGINT                           COMMENT '读字节数',
    `write_bytes`      BIGINT                           COMMENT '写字节数',
    `read_time`        BIGINT                           COMMENT '读时间',
    `write_time`       BIGINT                           COMMENT '写时间',
    `io_time`          BIGINT                           COMMENT 'io时间',
    `weight_io`        BIGINT                           COMMENT 'wio',
    `disk_total`       BIGINT                           COMMENT '磁盘空间',
    `disk_used`        BIGINT                           COMMENT '磁盘使用空间',
    `disk_free`        BIGINT                           COMMENT '磁盘空闲空间',
    `inode_total`      BIGINT                           COMMENT 'inode空间',
    `inode_used`       BIGINT                           COMMENT 'inode使用',
    `inode_free`       BIGINT                           COMMENT 'inode空闲',
    `date_time`        BIGINT                           COMMENT '创建日期',
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;