CREATE TABLE IF NOT EXISTS `monitor_host_indicator` (
    `id`                  BIGINT UNSIGNED AUTO_INCREMENT COMMENT 'id',
    `host_name`           VARCHAR(100)  NOT NULL           COMMENT '机器名称',
    `host_ip`             VARCHAR(100)  NOT NULL           COMMENT '机器IP',
    `procs`               BIGINT                           COMMENT '进程数量',
    `cpu_user`            FLOAT                            COMMENT '用户cpu时间',
    `cpu_sys`             FLOAT                            COMMENT '系统cpu时间',
    `cpu_idle`            FLOAT                            COMMENT 'cpu空闲时间',
    `cpu_iowait`          FLOAT                            COMMENT 'iowait',
    `cpu_irq`             FLOAT         NOT NULL           COMMENT '硬件中断',
    `cpu_sofirg`          FLOAT                            COMMENT '软件中断',
    `load1`               FLOAT                            COMMENT '1分钟平均负载',
    `load5`               FLOAT                            COMMENT '5分钟平均负载',
    `load15`              FLOAT                            COMMENT '15平均负载',
    `load_process_total`  FLOAT                            COMMENT '总进程数',
    `load_process_run`    FLOAT                            COMMENT '运行进程数',
    `mem_swap_total`      FLOAT                            COMMENT '内存交换区总量',
    `mem_swap_used`       FLOAT                            COMMENT '内存交换区使用量',
    `mem_swap_free`       FLOAT                            COMMENT '内存交换区空闲量',
    `mem_swap_percent`    FLOAT                            COMMENT '内存交换区使用占比',
    `mem_vtotal`          FLOAT                            COMMENT '内存总量',
    `mem_vused`           FLOAT                            COMMENT '内存使用量',
    `mem_vfree`           FLOAT                            COMMENT '内存空闲量',
    `mem_vpercent`        FLOAT                            COMMENT '内存使用占比',
    `net_traffic_rev`     BIGINT                           COMMENT '网络流入流量',
    `net_traffic_sent`    BIGINT                           COMMENT '网络流出流量',
    `net_package_rev`     BIGINT                           COMMENT '网络流入包数量',
    `net_package_sent`    BIGINT                           COMMENT '网络流出包数量',
    `net_drop_rev`        BIGINT                           COMMENT '网络流入丢包数量',
    `net_drop_sent`       BIGINT                           COMMENT '网络流出丢包数量',
    `net_error_rev`       BIGINT                           COMMENT '网络流入错误包数量',
    `net_error_sent`      BIGINT                           COMMENT '网络流出错误包数量',
    `disk_read_count`     BIGINT                           COMMENT '磁盘读取次数',
    `disk_write_count`    BIGINT                           COMMENT '磁盘写入次数',
    `disk_read_bytes`     BIGINT                           COMMENT '磁盘读取流量',
    `disk_write_bytes`    BIGINT                           COMMENT '磁盘写入流量',
    `disk_read_time`      BIGINT                           COMMENT '磁盘读取时间',
    `disk_write_time`     BIGINT                           COMMENT '磁盘写入时间',
    `io_time`             BIGINT                           COMMENT 'io时间',
    `disk_total`          BIGINT                           COMMENT '磁盘总量',
    `disk_used`           BIGINT                           COMMENT '磁盘使用量',
    `disk_free`           BIGINT                           COMMENT '磁盘空闲量',
    `inode_total`         BIGINT                           COMMENT 'inode总数',
    `inode_used`          BIGINT                           COMMENT 'inode使用数',
    `inode_free`          BIGINT                           COMMENT 'inode空闲数',
    `date_time`           BIGINT        NOT NULL           COMMENT '时间点',
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;